services:
  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build: ./discovery-service
    ports:
      - "8761:8761"
    hostname: discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - microservices-network

  config-service:
    container_name: config-server
    image: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - microservices-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - microservices-network
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-network
    depends_on:
      - mysql

  profile-service:
    container_name: profile-service
    image: profile-service
    build: ./profile-service
    ports:
      - "8091:8091"
    environment:
      - HOSTNAME=profile-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/profileService?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - discovery-service
      - mysql
    networks:
      - microservices-network

  Pnier-service:
    container_name: Panier-service
    image: Panier-service
    build: ./mini_projet_panier
    ports:
      - "8081:8081"
    environment:
      - HOSTNAME=Panier-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce_panier?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - discovery-service
      - mysql
    networks:
      - microservices-network

  reclamation-service:
    container_name: reclamation-service
    image: reclamation-service
    build: ./MicroServiceReclamation
    ports:
      - "8085:8085"
    environment:
      - HOSTNAME=reclamation-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - microservices-network

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build: ./api-gateway
    ports:
      - "8222:8222"
    environment:
      - HOSTNAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - profile-service
      - reclamation-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data: